---
title: "Having fun playing with Twitter data"
author: "Kelly Sovacool"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output:
  html_document:
    theme: "yeti"
    toc: true
    toc_float: true
github-repo: kelly-sovacool/twitter-stats
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = 'figures/'
)
```


```{r deps, message = FALSE}
library(here)
library(tidyverse)
library(rtweet)
```

```{r authenticate, eval = FALSE}
auth_setup_default()
```

```{r get_my_tweets}
my_username <- 'kelly_sovacool'
me <- lookup_users(my_username)
num_tweets <- me[['statuses_count']]
#my_tweets_all <- get_timeline(user = me[['id']], n = num_tweets, retryonratelimit = TRUE) # Error: $ operator is invalid for atomic vectors 
my_tweets <- get_timeline(user = me[['id']],
                          n = 1163, # 1164 failed, 1163 worked
                          retryonratelimit = TRUE)
my_tweets_orig <- my_tweets %>% 
  filter(!startsWith(text, 'RT @')) # no retweets
my_tweets_orig_noreplies <- my_tweets_orig %>% 
    filter(is.na(in_reply_to_status_id)) # no replies
```

Why does `get_timeline` fail  for my account with `n > 1163`?

```{r investigate, warning=TRUE, eval=FALSE}
oldest_tweet <- my_tweets[nrow(my_tweets), ]
print(oldest_tweet[['id_str']]) # this will change as I tweet more
# https://twitter.com/kelly_sovacool/status/1105862504889110534
older_tweets <- get_timeline(user = me[['id']],
                             n = 1,
                             max_id = "1105862504889110534")
```

this might be fixed by https://github.com/ropensci/rtweet/pull/627

```{r fixattempt, warning=TRUE, eval=FALSE}
#devtools::install_github('ropensci/rtweet@coordinates')
my_tweets_all <- get_timeline(user = me[['id']], n = num_tweets, retryonratelimit = TRUE)
```

uh nope didn't work. will continue using tweets newer than "1105862504889110534"

## most liked tweets

```{r}
print_embed <- function(status_id, tcount, screen_name = 'kelly_sovacool', 
                        type = 'likes', n = 1) {
  emoji <- if_else(type == 'likes', 'â¤ï¸','ðŸ”')
  cat('#### ', n, ".  ", emoji, '**', tcount, '**\n',
      tweet_embed(screen_name = screen_name, status_id = status_id),
      sep = "")
}
```


```{r most_liked, results = 'asis'}
most_liked <- my_tweets_orig %>% 
    slice_max(favorite_count, n = 5)
n <- 0
embeds <- 
    apply(most_liked, MARGIN = 1, 
           function(tweet) { 
             n <<- n + 1
             print_embed(tweet[['id_str']], tweet[['favorite_count']], 
                         type = 'likes', n = n)
               })
```


## most retweeted tweets

```{r most_rtd, results = 'asis'}
most_rtd <- my_tweets_orig %>% 
    slice_max(retweet_count, n = 5)
n <- 0
embeds <- 
    apply(most_rtd, MARGIN = 1, 
           function(tweet) { 
             n <<- n + 1
             print_embed(tweet[['id_str']], tweet[['retweet_count']], 
                         type = 'retweets', n = n)
               })
```

## plots!

```{r plot_hist}
my_tweets_orig_noreplies %>% 
    pivot_longer(c(favorite_count, retweet_count),
                 names_to = 'engagement_type',
                 values_to = 'engagement_count') %>% 
    ggplot(aes(engagement_count, fill = engagement_type)) +
    geom_histogram(alpha = 0.7) +
    facet_wrap('engagement_type', nrow = 1) +
    labs(x = '') +
    theme_bw() +
    theme(legend.position = 'none')
```

```{r plot_likes-vs-RTs}
my_tweets_orig_noreplies %>% 
  ggplot(aes(retweet_count, favorite_count)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_smooth(show.legend = FALSE) +
  theme_bw()
```

```{r plot_time}
my_tweets_orig_noreplies %>% 
  mutate(created_datetime = lubridate::as_datetime(created_at, format = '%a %b %d %H:%M:%S +0000 %Y')) %>% 
  pivot_longer(c(favorite_count, retweet_count),
               names_to = 'engagement_type',
               values_to = 'engagement_count') %>% 
  ggplot(aes(created_datetime, engagement_count, color = engagement_type)) +
  geom_smooth(show.legend = FALSE) +
  geom_point(alpha = 0.5, size = 2) +
  scale_x_datetime(date_breaks = "3 months", date_labels = "%b %Y") + 
  labs(y='', x='') +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = 'bottom',
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
